### ISSUE TITLE
Unable to retrieve log report

### ISSUE THREAD

**Issue by Sai-1411** [Ricksoft-OSS/audit-log-browser#13]
Hi,

**@silverskyvicto @shishi999** 
    **Thankyou for providing this add-on.**

After installing the add-on, we are encountering difficulties accessing the report within the application. Could you please provide us with guidance or parameters to correctly fill in the fields provided in the log form?

We are using **Alfresco 5.2.g.** Despite trying different versions of the add-ons, we continue to experience the same errors. Specifically, we are unable to access the log report in the Admin Tools tab.

We have tried all these add-ons version for our application where we are getting the same errors.
audit-log-browser-share-jar-1.0.3.jar           audit-log-browser-share-jar-1.0.2.jar            audit-log-browser-share-jar-1.0.1.jar
audit-log-browser-platform-jar-1.0.3.jar      audit-log-browser-platform-jar-1.0.2.jar       audit-log-browser-platform-jar-1.0.1.jar
While trying to get the report we are getting the **below error** and **attached a Screen shot**

2024-03-30 13:22:11,543 **ERROR** [org.springframework.extensions.webscripts.AbstractRuntime] [http-apr-8080-exec-5] Exception from executeScript: 02300002 Unable to locate resource resource for :audit-applications audit-entries
org.alfresco.rest.framework.core.exceptions.NotFoundException: 02300002 Unable to locate resource resource for :audit-applications audit-entries
	at org.alfresco.rest.framework.core.ResourceLookupDictionary.locateRelationResource(ResourceLookupDictionary.java:113)
	at org.alfresco.rest.framework.core.ResourceLookupDictionary.locateResource(ResourceLookupDictionary.java:144)
	at org.alfresco.rest.api.PublicApiDeclarativeRegistry.getResourceWithMetadataOrNull(PublicApiDeclarativeRegistry.java:263)
	at org.alfresco.rest.api.PublicApiDeclarativeRegistry.findWebScript(PublicApiDeclarativeRegistry.java:124)
	at org.springframework.extensions.webscripts.AbstractRuntime.executeScript(AbstractRuntime.java:165)
	at org.alfresco.repo.web.scripts.TenantWebScriptServlet.service(TenantWebScriptServlet.java:82)
	at org.alfresco.rest.api.PublicApiWebScriptServlet.service(PublicApiWebScriptServlet.java:62)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.alfresco.module.aosmodule.service.ContextRootFilter.doFilter(ContextRootFilter.java:93)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.alfresco.repo.web.filter.beans.NullFilter.doFilter(NullFilter.java:75)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.alfresco.repo.management.subsystems.ChainingSubsystemProxyFactory$1.invoke(ChainingSubsystemProxyFactory.java:132)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:204)
	at com.sun.proxy.$Proxy234.doFilter(Unknown Source)
	at org.alfresco.repo.web.filter.beans.BeanProxyFilter.doFilter(BeanProxyFilter.java:89)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.alfresco.web.app.servlet.GlobalLocalizationFilter.doFilter(GlobalLocalizationFilter.java:68)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:218)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:110)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:506)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:169)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:962)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:445)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1115)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:637)
	at org.apache.tomcat.util.net.AprEndpoint$SocketProcessor.doRun(AprEndpoint.java:2549)
	at org.apache.tomcat.util.net.AprEndpoint$SocketProcessor.run(AprEndpoint.java:2538)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Unknown Source)

![Screenshot 2024-03-30 134627](https://github.com/Ricksoft-OSS/audit-log-browser/assets/113694601/32aa102a-0f7e-4a87-9332-8bf444a6931f)

Can you please guide us in resolving this issue.

Thankyou & Regards 
     Sai Kumar S

**Comment by shishi999** [comment]
Hello @Sai-1411.
Thank you for your interest!

As the release page shows, "5.2.g" is not supported, because this version does not have any functions to record audit entries, as far as I know (it's an old memory, so I'm not sure, but I think it was...).

Regards,
Shogo

**Comment by shishi999** [comment]
For your information, the latest version of the Community Edition has the ability to record audit logs. This add-on may work with this version.

**Comment by Sai-1411** [comment]
Hi **@shishi999** 
**Thank you for your support and guidance.**

Could you please **provide information about the parameters** that need to be filled in the content field or provide an **example of how to fill all the parameters?** Additionally, how would the **results appear?**

For the **Alfresco 6.2 edition**, which version of the **JAR file** should I use?

Thanks & regards
Sai Kumar S

**Comment by shishi999** [comment]
@Sai-1411 
> Could you please provide information about the parameters that need to be filled in the content field or provide an example of how to fill all the parameters? 

In the Contents field, type the filename of the file you want to find to view audit logs. Note that searching in the Contents field does not support partial searches.
_ex.) Book5.xlsx_
( "Book5" is NG. )

>how would the results appear?

This is sample.
It might be a good idea to show this screenshot.
![image](https://github.com/Ricksoft-OSS/audit-log-browser/assets/5299416/b48277ff-5b92-4434-bddc-1f86955b97a4)

>For the Alfresco 6.2 edition, which version of the JAR file should I use?

Sorry, 6.x isn't tested. v.2.0.0 may work.
I'll check it.

Regards,
Shogo

**Comment by Sai-1411** [comment]
**Thank you @shishi999** for helping us in resolving the issues 

We have **tested** in **Alfresco 6.2 version** - **v.2.0.0** is **working** but the problem we are facing is that we are unable to **download the log report** we are getting the below **error** can you check this once 

2024-04-01 11:27:45,878 ERROR [org.springframework.extensions.webscripts.AbstractRuntime] [http-nio-8080-exec-8] Exception from executeScript: 03010024 Wrapped Exception (with status template): org/apache/commons/csv/CSVFormat
org.springframework.extensions.webscripts.WebScriptException: 03010024 Wrapped Exception (with status template): org/apache/commons/csv/CSVFormat
	at org.springframework.extensions.webscripts.AbstractWebScript.createStatusException(AbstractWebScript.java:1139)
	at org.springframework.extensions.webscripts.DeclarativeWebScript.execute(DeclarativeWebScript.java:171)
	at org.alfresco.repo.web.scripts.RepositoryContainer$3.execute(RepositoryContainer.java:527)
	at org.alfresco.repo.transaction.RetryingTransactionHelper.doInTransaction(RetryingTransactionHelper.java:450)
	at org.alfresco.repo.web.scripts.RepositoryContainer.transactionedExecute(RepositoryContainer.java:595)
	at org.alfresco.repo.web.scripts.RepositoryContainer.transactionedExecuteAs(RepositoryContainer.java:664)
	at org.alfresco.repo.web.scripts.RepositoryContainer.executeScriptInternal(RepositoryContainer.java:435)
	at org.alfresco.repo.web.scripts.RepositoryContainer.executeScript(RepositoryContainer.java:315)
	at org.springframework.extensions.webscripts.AbstractRuntime.executeScript(AbstractRuntime.java:399)
	at org.springframework.extensions.webscripts.AbstractRuntime.executeScript(AbstractRuntime.java:210)
	at org.springframework.extensions.webscripts.servlet.WebScriptServlet.service(WebScriptServlet.java:132)
	at org.alfresco.repo.web.scripts.AlfrescoWebScriptServlet.service(AlfrescoWebScriptServlet.java:43)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:623)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:209)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
	at org.alfresco.web.app.servlet.GlobalLocalizationFilter.doFilter(GlobalLocalizationFilter.java:68)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
	at org.alfresco.web.app.servlet.ClearSecurityContextFilter.doFilter(ClearSecurityContextFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:167)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:481)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:130)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:673)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:390)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:926)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1791)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.NoClassDefFoundError: org/apache/commons/csv/CSVFormat
	at jp.ricksoft.auditlogbrowser.file.CSVManager.addRecord(CSVManager.java:123)
	at jp.ricksoft.auditlogbrowser.file.CSVManager.lambda$createOneDayAuditLogCSV$2(CSVManager.java:168)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at jp.ricksoft.auditlogbrowser.file.CSVManager.createOneDayAuditLogCSV(CSVManager.java:168)
	at jp.ricksoft.auditlogbrowser.audit.download.DownloadAuditLogZipHandler.createAuditLogsZip(DownloadAuditLogZipHandler.java:125)
	at jp.ricksoft.auditlogbrowser.audit.download.DownloadAuditLogZipHandler.execExport(DownloadAuditLogZipHandler.java:95)
	at jp.ricksoft.auditlogbrowser.webscript.DownloadAuditLogZipWebScript.executeImpl(DownloadAuditLogZipWebScript.java:50)
	at org.springframework.extensions.webscripts.DeclarativeWebScript.execute(DeclarativeWebScript.java:64)
	... 39 more

Thanks & regards
Sai Kumar S

**Comment by shishi999** [comment]
@Sai-1411 

Oh... I see it. 
Apache Commons CSV has been updated between 6.x and 7.x, so it is not interchangeable with 6.x.
6.x cannot be supported, I'm sorry...

**Comment by Sai-1411** [comment]
**Thanks... @shishi999** 
But is any other way that we can download the report.. It will be more helpful else everything working fine...
If we able to download the report our requirement will close.. So just **generating the report and downloading it in excel** is the goal for us
We tried adding a jar file named: **commons-csv-1.9.0**     
After adding this file in lib folder in both **share** and **alfresco**
It is generating in alf_data/auditlogbrowser in the zip format but when we try to open it it is showing corrupted archive/file.

Please Help me achieving it it will be great help...

Thanks
@Sai-1411
