### ISSUE TITLE
Error starting up the plugin then "mail.testmessage.send=true"

### ISSUE THREAD

**Issue by iohann95** [Ricksoft-OSS/audit-log-browser#15]
Hello. Thanks for this great add-on.

When I define on my ACS "mail.testmessage.send=true" (So that Alfresco send an e-mail every time the system starts up) the plugin fails to be deployed.
It works OK when it's not defined or it's "false"

I tested on ACS 7.2 and 7.3 and the behavior is the same.

```
alfresco-1            | 2024-04-12 10:28:38,055  ERROR [audit.model.AuditModelRegistryImpl] [main] Failed to load audit model: jar:file:/usr/local/tomcat/webapps/alfresco/WEB-INF/lib/audit-log-browser-platform-2.0.0.jar!/alfresco/extension/audit/share-site-audit-app.xml
alfresco-1            | org.alfresco.repo.audit.model.AuditModelException: 03120000 No registered audit data extractor exists for 'jp.ricksoft.siteExtractor'.
alfresco-1            |         at org.alfresco.repo.audit.model.AuditModelRegistryImpl$AuditModelRegistryState.cacheAuditElements(AuditModelRegistryImpl.java:568)
alfresco-1            |         at org.alfresco.repo.audit.model.AuditModelRegistryImpl$AuditModelRegistryState.access$1(AuditModelRegistryImpl.java:521)
alfresco-1            |         at org.alfresco.repo.audit.model.AuditModelRegistryImpl$AuditModelRegistryState$1.execute(AuditModelRegistryImpl.java:433)
alfresco-1            |         at org.alfresco.repo.audit.model.AuditModelRegistryImpl$AuditModelRegistryState$1.execute(AuditModelRegistryImpl.java:1)
alfresco-1            |         at org.alfresco.repo.transaction.RetryingTransactionHelper.doInTransaction(RetryingTransactionHelper.java:452)
alfresco-1            |         at org.alfresco.repo.audit.model.AuditModelRegistryImpl$AuditModelRegistryState$2.doWork(AuditModelRegistryImpl.java:460)
alfresco-1            |         at org.alfresco.repo.audit.model.AuditModelRegistryImpl$AuditModelRegistryState$2.doWork(AuditModelRegistryImpl.java:1)
alfresco-1            |         at org.alfresco.repo.security.authentication.AuthenticationUtil.runAs(AuthenticationUtil.java:602)
alfresco-1            |         at org.alfresco.repo.audit.model.AuditModelRegistryImpl$AuditModelRegistryState.start(AuditModelRegistryImpl.java:456)
alfresco-1            |         at org.alfresco.repo.management.subsystems.AbstractPropertyBackedBean.start(AbstractPropertyBackedBean.java:1098)
alfresco-1            |         at org.alfresco.repo.management.subsystems.AbstractPropertyBackedBean.getState(AbstractPropertyBackedBean.java:320)
alfresco-1            |         at org.alfresco.repo.audit.model.AuditModelRegistryImpl.getAuditPathMapper(AuditModelRegistryImpl.java:226)
alfresco-1            |         at org.alfresco.repo.audit.AuditComponentImpl.areAuditValuesRequired(AuditComponentImpl.java:302)
alfresco-1            |         at org.alfresco.repo.audit.AuditMethodInterceptor.invoke(AuditMethodInterceptor.java:164)
alfresco-1            |         at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
alfresco-1            |         at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123)
alfresco-1            |         at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:388)
alfresco-1            |         at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119)
alfresco-1            |         at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
alfresco-1            |         at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:215)
alfresco-1            |         at jdk.proxy3/jdk.proxy3.$Proxy55.createAction(Unknown Source)
alfresco-1            |         at org.alfresco.repo.action.executer.MailActionExecuter$1.doWork(MailActionExecuter.java:455)
alfresco-1            |         at org.alfresco.repo.security.authentication.AuthenticationUtil.runAs(AuthenticationUtil.java:602)
alfresco-1            |         at org.alfresco.repo.action.executer.MailActionExecuter.init(MailActionExecuter.java:446)
alfresco-1            |         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
alfresco-1            |         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
alfresco-1            |         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
alfresco-1            |         at java.base/java.lang.reflect.Method.invoke(Method.java:568)
alfresco-1            |         at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.lambda$invokeCustomInitMethod$7(AbstractAutowireCapableBeanFactory.java:1920)
alfresco-1            |         at java.base/java.security.AccessController.doPrivileged(AccessController.java:712)
alfresco-1            |         at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeCustomInitMethod(AbstractAutowireCapableBeanFactory.java:1919)
alfresco-1            |         at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1872)
alfresco-1            |         at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1800)
alfresco-1            |         at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:620)
alfresco-1            |         at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
alfresco-1            |         at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
alfresco-1            |         at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
alfresco-1            |         at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
alfresco-1            |         at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
alfresco-1            |         at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:955)
alfresco-1            |         at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:918)
alfresco-1            |         at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583)
alfresco-1            |         at org.alfresco.repo.management.subsystems.ChildApplicationContextFactory$ApplicationContextState.start(ChildApplicationContextFactory.java:824)
alfresco-1            |         at org.alfresco.repo.management.subsystems.AbstractPropertyBackedBean.start(AbstractPropertyBackedBean.java:1098)
alfresco-1            |         at org.alfresco.repo.management.subsystems.AbstractPropertyBackedBean.getState(AbstractPropertyBackedBean.java:320)
alfresco-1            |         at org.alfresco.repo.management.subsystems.ChildApplicationContextFactory.getApplicationContext(ChildApplicationContextFactory.java:450)
alfresco-1            |         at org.alfresco.repo.management.subsystems.SubsystemProxyFactory.locateBean(SubsystemProxyFactory.java:181)
alfresco-1            |         at org.alfresco.repo.management.subsystems.SubsystemProxyFactory$1.invoke(SubsystemProxyFactory.java:79)
alfresco-1            |         at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
alfresco-1            |         at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:215)
alfresco-1            |         at jdk.proxy3/jdk.proxy3.$Proxy191.getActionDefinition(Unknown Source)
alfresco-1            |         at org.alfresco.module.org_alfresco_module_rm.action.impl.DelegateAction.addParameterDefinitions(DelegateAction.java:102)
alfresco-1            |         at org.alfresco.repo.action.ParameterizedItemAbstractBase.getLocalizedParameterDefinitions(ParameterizedItemAbstractBase.java:115)
alfresco-1            |         at org.alfresco.repo.action.executer.ActionExecuterAbstractBase.getActionDefinition(ActionExecuterAbstractBase.java:248)
alfresco-1            |         at org.alfresco.module.org_alfresco_module_rm.action.RMActionExecuterAbstractBase.getActionDefinition(RMActionExecuterAbstractBase.java:546)
alfresco-1            |         at org.alfresco.module.org_alfresco_module_rm.action.AuditableActionExecuterAbstractBase.init(AuditableActionExecuterAbstractBase.java:132)
alfresco-1            |         at org.alfresco.module.org_alfresco_module_rm.action.RMActionExecuterAbstractBase.init(RMActionExecuterAbstractBase.java:579)
alfresco-1            |         at jdk.internal.reflect.GeneratedMethodAccessor180.invoke(Unknown Source)
alfresco-1            |         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
alfresco-1            |         at java.base/java.lang.reflect.Method.invoke(Method.java:568)
alfresco-1            |         at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.lambda$invokeCustomInitMethod$7(AbstractAutowireCapableBeanFactory.java:1920)
alfresco-1            |         at java.base/java.security.AccessController.doPrivileged(AccessController.java:712)
alfresco-1            |         at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeCustomInitMethod(AbstractAutowireCapableBeanFactory.java:1919)
alfresco-1            |         at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1872)
alfresco-1            |         at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1800)
alfresco-1            |         at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:620)
alfresco-1            |         at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
alfresco-1            |         at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
alfresco-1            |         at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
alfresco-1            |         at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
alfresco-1            |         at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
alfresco-1            |         at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveReference(BeanDefinitionValueResolver.java:330)
alfresco-1            |         at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveValueIfNecessary(BeanDefinitionValueResolver.java:113)
alfresco-1            |         at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyPropertyValues(AbstractAutowireCapableBeanFactory.java:1707)
alfresco-1            |         at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1452)
alfresco-1            |         at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:619)
alfresco-1            |         at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
alfresco-1            |         at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
alfresco-1            |         at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
alfresco-1            |         at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
alfresco-1            |         at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
alfresco-1            |         at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:936)
alfresco-1            |         at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:918)
alfresco-1            |         at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583)
alfresco-1            |         at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:401)
alfresco-1            |         at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:292)
alfresco-1            |         at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:103)
alfresco-1            |         at org.alfresco.web.app.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:70)
alfresco-1            |         at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4768)
alfresco-1            |         at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5230)
alfresco-1            |         at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
alfresco-1            |         at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:726)
alfresco-1            |         at org.apache.catalina.core.ContainerBase.access$000(ContainerBase.java:129)
alfresco-1            |         at org.apache.catalina.core.ContainerBase$PrivilegedAddChild.run(ContainerBase.java:149)
alfresco-1            |         at org.apache.catalina.core.ContainerBase$PrivilegedAddChild.run(ContainerBase.java:139)
alfresco-1            |         at java.base/java.security.AccessController.doPrivileged(AccessController.java:318)
alfresco-1            |         at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:696)
alfresco-1            |         at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:696)
alfresco-1            |         at org.apache.catalina.startup.HostConfig.deployDirectory(HostConfig.java:1185)
alfresco-1            |         at org.apache.catalina.startup.HostConfig$DeployDirectory.run(HostConfig.java:1933)
alfresco-1            |         at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
alfresco-1            |         at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
alfresco-1            |         at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
alfresco-1            |         at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:123)
alfresco-1            |         at org.apache.catalina.startup.HostConfig.deployDirectories(HostConfig.java:1095)
alfresco-1            |         at org.apache.catalina.startup.HostConfig.deployApps(HostConfig.java:477)
alfresco-1            |         at org.apache.catalina.startup.HostConfig.start(HostConfig.java:1618)
alfresco-1            |         at org.apache.catalina.startup.HostConfig.lifecycleEvent(HostConfig.java:319)
alfresco-1            |         at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:123)
alfresco-1            |         at org.apache.catalina.util.LifecycleBase.setStateInternal(LifecycleBase.java:423)
alfresco-1            |         at org.apache.catalina.util.LifecycleBase.setState(LifecycleBase.java:366)
alfresco-1            |         at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:946)
alfresco-1            |         at org.apache.catalina.core.StandardHost.startInternal(StandardHost.java:835)
alfresco-1            |         at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
alfresco-1            |         at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1396)
alfresco-1            |         at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1386)
alfresco-1            |         at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
alfresco-1            |         at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
alfresco-1            |         at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:145)
alfresco-1            |         at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:919)
alfresco-1            |         at org.apache.catalina.core.StandardEngine.startInternal(StandardEngine.java:263)
alfresco-1            |         at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
alfresco-1            |         at org.apache.catalina.core.StandardService.startInternal(StandardService.java:432)
alfresco-1            |         at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
alfresco-1            |         at org.apache.catalina.core.StandardServer.startInternal(StandardServer.java:927)
alfresco-1            |         at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
alfresco-1            |         at org.apache.catalina.startup.Catalina.start(Catalina.java:772)
alfresco-1            |         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
alfresco-1            |         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
alfresco-1            |         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
alfresco-1            |         at java.base/java.lang.reflect.Method.invoke(Method.java:568)
alfresco-1            |         at org.apache.catalina.startup.Bootstrap.start(Bootstrap.java:345)
alfresco-1            |         at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:476)
```

**Comment by shishi999** [comment]
Hi @iohann95  -san,
Thanks for your report!

I'm looking into this issue right now.

Well, we couldn't reproduce this issue. 
To reproduce this, we set java options in "docker/docker-compose.yml" as shown below.
```
JAVA_OPTS: '
        -Dsolr.secureComms=secret
        -Dsolr.sharedSecret=secret
        -Dfile.encoding=UTF-8
        -Dmail.testmessage.send=true
        -Dmessaging.broker.url="failover:(nio://audit-log-browser-activemq:61616)?timeout=3000&jms.useCompression=true"
        '
```
But ACS started correctly.

It looks like you are using Docker Compose to deploy ACS. Could you give me the docker-compose.yml file or tell me your ACS architecture?

**Comment by iohann95** [comment]
Good afternoon!

Thank you for taking a look on this case.

This is my ACS configuration.

Let me know if you want more information, or even a video recording of the error, or if you want send me a message on my discord @hrrs_95

```yml
    alfresco:
        build:
          context: ./alfresco
          args:
            ALFRESCO_TAG: ${ALFRESCO_CE_TAG}
            DB: postgres
            SOLR_COMMS: secret 
        mem_limit: 7488m
        restart: on-failure
        depends_on: 
            - postgres  
        environment:
            JAVA_TOOL_OPTIONS: "
                -Dencryption.keystore.type=JCEKS
                -Dencryption.cipherAlgorithm=DESede/CBC/PKCS5Padding
                -Dencryption.keyAlgorithm=DESede
                -Dencryption.keystore.location=/usr/local/tomcat/shared/classes/alfresco/extension/keystore/keystore
                -Dmetadata-keystore.password=mp6yc0UD9e
                -Dmetadata-keystore.aliases=metadata
                -Dmetadata-keystore.metadata.password=oKIWzVdEdA
                -Dmetadata-keystore.metadata.algorithm=DESede
                "
            JAVA_OPTS : '
                -Ddb.username=alfresco
                -Ddb.password=alfresco
                -Ddb.driver=org.postgresql.Driver
                -Ddb.url=jdbc:postgresql://postgres:5432/alfresco  
                -Dalfresco_user_store.adminpassword=209c6174da490caeb422f3fa5a7ae634
                -Dsystem.preferred.password.encoding=bcrypt10
                -Dsolr.host=solr6
                -Dsolr.port=8983
                -Dsolr.port.ssl=8983
                -Dsolr.secureComms=secret
                -Dsolr.baseUrl=/solr
                -Dindex.subsystem.name=solr6
                -Dsolr.sharedSecret=o8kofnkgwvs  
                -Dalfresco.host=${SERVER_NAME}
                -Dalfresco.port=443
                -Dapi-explorer.url=https://${SERVER_NAME}:443/api-explorer
                -Dalfresco.protocol=https 
                -Dshare.host=${SERVER_NAME}
                -Dshare.port=443
                -Dshare.protocol=https 
                -Daos.baseUrlOverwrite=https://${SERVER_NAME}/alfresco/aos
                -Dmessaging.broker.url="failover:(nio://activemq:61616)?timeout=3000&jms.useCompression=true"
                -Ddeployment.method=DOCKER_COMPOSE
                -Dcsrf.filter.enabled=false 
                -Dopencmis.server.override=true
                -Dopencmis.server.value=https://${SERVER_NAME}:443
                -DlocalTransform.core-aio.url=http://transform-core-aio:8090/ 
                -Dcsrf.filter.enabled=false
                -Dalfresco.restApi.basicAuthScheme=true
                -XX:+UseG1GC -XX:+UseStringDeduplication
                -Dgoogledocs.enabled=true 
                -Xms6976m -Xmx6976m 
                -XX:MinRAMPercentage=50 -XX:MaxRAMPercentage=80
                -Dmail.host=smtp.gmail.com
                -Dmail.port=587
                -Dmail.username=**********REDACTED**********
                -Dmail.from.enabled=true
                -Dmail.from.default=**********REDACTED**********
                -Dmail.password=**********REDACTED**********
                -Dmail.protocol=smtp
                -Dmail.encoding=UTF-8
                -Dmail.smtp.auth=true
                -Dmail.smtp.starttls.enable=true
                -Dmail.testmessage.send=true
                -Dmail.testmessage.to=**********REDACTED**********
                -Dmail.testmessage.subject="TEST SERVER"
                -Dmail.testmessage.text="SERVER STARTED UP"
                -Daudit.enabled=true
                -Daudit.rm.enabled=true
                -Daudit.alfresco-access.sub-actions.enabled=true
                -Daudit.alfresco-access.enabled=true
                -Daudit.filter.alfresco-access.default.enabled=true
                -Daudit.filter.alfresco-access.transaction.type="cm:folder;cm:content;st:site;~cm:person"
                -Daudit.filter.alfresco-access.default.user="~System;~null;.*"
                -Daudit.filter.alfresco-access.transaction.user="~System;~null;.*"
            '
        volumes: 
            - ./data/alf-repo-data:/usr/local/tomcat/alf_data
            - ./logs/alfresco:/usr/local/tomcat/logs    
```

**Comment by shishi999** [comment]
@iohann95 -san,
Thanks for the additional information.

I've deployed ACS 7.1 with the same options but the bug is not reproduced.
Then I found the post like your situation.
https://hub.alfresco.com/t5/alfresco-content-services-forum/audit-dataextractor-custom-no-registered/td-p/314100

According to this, I wonder if it cannot be resolved from module side...
Is AGS (Alfresco Governance Services) installed in your environment?

**Comment by shishi999** [comment]
OK, I've succeeded to reproduce it.
The reproduction step is shown below.

1. Install AGS(or Record Management)
2. [Add custom data extractors with any way](https://docs.alfresco.com/content-services/6.0/develop/repo-ext-points/audit-log/)(jar, xml)
3. Set java property "mail.testmessage.send=true"
4. Start ACS and deploying a custom audit application is failed. ( "rm" is also failed)

The codes to reproduce is [here](https://github.com/shishi999/error-reproduction-of-acs-audit)

I'll report this issue to Hyland Support...

**Comment by iohann95** [comment]
Yes I do have AGS, I forgot to mention it.

Thank you very much!
